# This is a basic workflow to help you get started with Actions
name: Upload apk to Waldo

defaults:
  run:
    working-directory: apps/expo

# Controls when the workflow will run
on:
  # Triggers the workflow on push/merge request events but only for the "staging" branch
  push:
    branches: ["staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build apk
        uses: realabbas/Github-Actions-React-Native@v1.1.2
        run: |
          yarn waldo:build && cd android/ && chmod +x ./gradlew && STAGE=development ./gradlew assembleDebug \

          echo "APK_PATH=$(pwd)/app/build/outputs/apk/app-debug.apk" >>$GITHUB_ENV

      - name: Upload build to Waldo
        uses: waldoapp/gh-action-upload@v1
        with:
          build_path: ${{ env.APK_PATH }}
          upload_token: ${{ secrets.WALDO_UPLOAD_TOKEN }}
          is_debug_mode: true
